version: '3.8'

services:
  connectteam:
    build: ./
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_USERNAME=postgres
    ports:
      - 5436:5432
