DROP TABLE IF EXISTS users;
DROP TYPE IF EXISTS user_role;
DROP TABLE IF EXISTS plans_users;
DROP TABLE IF EXISTS plan_requests;
DROP TYPE IF EXISTS plans;
DROP TABLE IF EXISTS verification_codes;
DROP TABLE IF EXISTS topics;
DROP TYPE IF EXISTS access;