port: "8000"

service_port: "8001"

db:
  username: "postgres"
  host: "localhost"
  port: "5432"
  dbname: "connecteam"
  sslmode: "disable"

redis:
  host: "localhost"
  port: "6379"

yookassa:
  shop_id: "371284"

notification_service:
  host: "localhost:8081"
  path: "/ws"

client_origin: "https://connecteam.ru"