port: "5432"

db:
  username: "postgres"
  password: "qwerty"
  host: "localhost"
  port: "5436"
  dbname: "postgres"
  sslmode: "disable"

storage:
  endpoint: "localstack:4572"
  bucket: "file-storage"